### ISSUE TITLE
Issue scrolling to the bottom

### ISSUE THREAD

**Issue by pera** [andrewinci/free-retro#48]
On Firefox 103 in Linux I couldn't scroll all the way to the bottom of a column (it bounces back 1 or 2 em). I had to zoom out to reach a group vote + button.

**Comment by andrewinci** [comment]
Can you share more details on your scenario please? Which retro Step? Any screenshoot you can share?

**Comment by pera** [comment]
I'm unable to reproduce the problem now, will close this and reopen it if I figure out what was happening the other day
